### ISSUE TITLE
Torch1.7 | RuntimeError: Error compiling objects for extension

### ISSUE THREAD

**Issue by KiedaTamashi** [lbin/DCNv2#12]
Problem met when run ./make.sh to install DCNv2

I used the latest version of you which supports pytorch1.7
My environment (using anaconda virtual env):
ubuntu 18.04
python 3.7
pytorch 1.7
cudatoolkit 10.2

Error Message:
 ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/NAS/home01/tanzhenwei/anaconda3/envs/torch17/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1522, in _run_ninja_build
    env=env)
  File "/NAS/home01/tanzhenwei/anaconda3/envs/torch17/lib/python3.7/subprocess.py", line 481, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 69, in <module>
    cmdclass={"build_ext": torch.utils.cpp_extension.BuildExtension},
  File "/NAS/home01/tanzhenwei/anaconda3/envs/torch17/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/NAS/home01/tanzhenwei/anaconda3/envs/torch17/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/NAS/home01/tanzhenwei/anaconda3/envs/torch17/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/NAS/home01/tanzhenwei/anaconda3/envs/torch17/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/NAS/home01/tanzhenwei/anaconda3/envs/torch17/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/NAS/home01/tanzhenwei/anaconda3/envs/torch17/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/NAS/home01/tanzhenwei/anaconda3/envs/torch17/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/NAS/home01/tanzhenwei/anaconda3/envs/torch17/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/NAS/home01/tanzhenwei/anaconda3/envs/torch17/lib/python3.7/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/NAS/home01/tanzhenwei/anaconda3/envs/torch17/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 653, in build_extensions
    build_ext.build_extensions(self)
  File "/NAS/home01/tanzhenwei/anaconda3/envs/torch17/lib/python3.7/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/NAS/home01/tanzhenwei/anaconda3/envs/torch17/lib/python3.7/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/NAS/home01/tanzhenwei/anaconda3/envs/torch17/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "/NAS/home01/tanzhenwei/anaconda3/envs/torch17/lib/python3.7/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/NAS/home01/tanzhenwei/anaconda3/envs/torch17/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 482, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/NAS/home01/tanzhenwei/anaconda3/envs/torch17/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1238, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/NAS/home01/tanzhenwei/anaconda3/envs/torch17/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1538, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

Could you help me?

**Comment by ZhaoChongren** [comment]
I have this same problem,have you solved it?can you help me?

**Comment by lbin** [comment]
@XiaoSanGit @ZhaoChongren Did you try master branch?

**Comment by KiedaTamashi** [comment]
@lbin Yes, and I also try cuda10.1/python3.6 but failed.
And I  try to compile https://github.com/jinfagang/DCNv2_latest  https://github.com/MatthewHowe/DCNv2 with pytorch=1.6 or 1.7(I need pytorch>=1.6) as well but all failed. But it works for pytorch 1.4 on server.
Could you give some hints that may cause the compile error? My gcc version is 7.3 and I am using remote server of ubuntu 18.04 offered by my prof so I have no admin authority. Everything goes well on my own laptop with pytorch1.7... I am struck in this annoying environment problem for weeks.

**Comment by lbin** [comment]
Tested on ubuntu 18.04 server with python 3.7.6 torch 1.7.1 cuda10.2 gcc 7.5.0, everything is ok. Maybe try `conda install gcc_linux-64 gxx_linux-64` and reinstall torch with conda

**Comment by KiedaTamashi** [comment]
@lbin The cuda 10.2 is in conda virtual environment(installed by conda install cudatoolkit=10.2) or the local one(in /usr/local/cuda)? I will follow your suggestion and try again.

**Comment by lbin** [comment]
both for safety ~@XiaoSanGit

**Comment by KiedaTamashi** [comment]
It works.
The GCC will use the local CUDA version. And local Cuda version 10.1.104 does not work. 
Solved by updating Cuda from 10.1.104 to 10.1.243 (or other Cuda version if you don't need cuda10.1)

**Comment by lbin** [comment]
cuda 10.2 is a stable version.
