### ISSUE TITLE
test error in pytorch_1.5 branch

### ISSUE THREAD

**Issue by shuuchen** [lbin/DCNv2#14]
Hi,

Thanks for your src.
I am testing pytorch_1.5 branch, and the following error happens:

gpu test:
> $ python testcuda.py
error in modulated_deformable_im2col_cuda: invalid device function
Traceback (most recent call last):
  File "testcuda.py", line 284, in <module>
    example_dconv()
  File "testcuda.py", line 202, in example_dconv
    error.backward()
  File "/home/du/anaconda3/envs/pytorch1.5/lib/python3.7/site-packages/torch/tensor.py", line 198, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/du/anaconda3/envs/pytorch1.5/lib/python3.7/site-packages/torch/autograd/__init__.py", line 100, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`
Segmentation fault (コアダンプ)

cpu test:
> $ python testcpu.py
torch.Size([2, 64, 128, 128])
torch.Size([20, 32, 7, 7])
torch.Size([20, 32, 7, 7])
torch.Size([20, 32, 7, 7])
0.971507, 1.943013
0.971507, 1.943013
Zero offset passed
/home/du/anaconda3/envs/pytorch1.5/lib/python3.7/site-packages/torch/autograd/gradcheck.py:244: UserWarning: At least one of the inputs that requires gradient is not of double precision floating point. This check will likely fail if all the inputs are not of double precision floating point.
  'At least one of the inputs that requires gradient '
Traceback (most recent call last):
  File "testcpu.py", line 289, in <module>
    check_gradient_dpooling()
  File "testcpu.py", line 184, in check_gradient_dpooling
    eps=1e-4,
  File "/home/du/anaconda3/envs/pytorch1.5/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 291, in gradcheck
    'numerical:%s\nanalytical:%s\n' % (i, j, n, a))
  File "/home/du/anaconda3/envs/pytorch1.5/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 229, in fail_test
    raise RuntimeError(msg)
RuntimeError: Jacobian mismatch for output 0 with respect to input 0,
numerical:tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])
analytical:tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

Any help would be appreciated.

**Comment by lbin** [comment]
test code may not right, pls ignore it

**Comment by anthonyweidai** [comment]
No, it makes bug when I using DCNv2 in another network!
Also, RuntimeError: NOT compled with GPU support.

**Comment by lbin** [comment]
pls update your  pytorch to latest version

**Comment by fabrizioschiano** [comment]
I have the same problem: 

`Also, RuntimeError: NOT compled with GPU support.`

when I check my pytorch version with: 

` python -c "import torch; print(torch.__version__)" `

I get 

`1.9.1+cu102` 

Then, if I do: 

`python -c "import torch; print(torch.cuda.is_available())"`

I get:  

`True`

What am I doing wrong?
