### ISSUE TITLE
ValueError: underlying buffer has been detached

### ISSUE THREAD

**Issue by czjghost** [lbin/DCNv2#18]
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 72, in <module>
    cmdclass={"build_ext": torch.utils.cpp_extension.BuildExtension},
  File "D:\app4code\Anaconda3\lib\site-packages\setuptools\__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "D:\app4code\Anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "D:\app4code\Anaconda3\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "D:\app4code\Anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\app4code\Anaconda3\lib\distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "D:\app4code\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\app4code\Anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\app4code\Anaconda3\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
    _build_ext.run(self)
  File "D:\app4code\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "D:\app4code\Anaconda3\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "D:\app4code\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 708, in build_extensions
    build_ext.build_extensions(self)
  File "D:\app4code\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 194, in build_extensions
    self.build_extension(ext)
  File "D:\app4code\Anaconda3\lib\site-packages\setuptools\command\build_ext.py", line 205, in build_extension
    _build_ext.build_extension(self, ext)
  File "D:\app4code\Anaconda3\lib\distutils\command\build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "D:\app4code\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 690, in win_wrap_ninja_compile
    with_cuda=with_cuda)
  File "D:\app4code\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1359, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "D:\app4code\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1683, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "D:\app4code\Anaconda3\lib\site-packages\colorama\ansitowin32.py", line 59, in closed
    return stream.closed
ValueError: underlying buffer has been detached

**Comment by czjghost** [comment]
Run in win10-64bit with Git and Ninja have been installed successfully. So...why does this problem occur during “sh make.sh”?
